name: Checks

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - master

jobs:
    commit_lint:
      name: Lint commit messages
      runs-on: ubuntu-latest
      env:
        GITHUB_TOKEN: ${{ secrets.OTTO_TOKEN }}

      steps:
        - name: Check out code
          uses: actions/checkout@v2.3.0
          with:
            fetch-depth: 0
        - name: Lint commit messages
          uses: wagoid/commitlint-github-action@v1
          with:
            failOnWarnings: true

    test_build:
      name: Test Docker build
      runs-on: ubuntu-latest

      steps:
        - name: Checkout code
          uses: actions/checkout@v2.3.0

        - name: Test build
          run: make docker-build

    auto_merge_dependabot:
        name: Auto-approve dependabot pull requests
        runs-on: ubuntu-latest
        needs: [test_build]

        if: github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]'

        steps:
          - name: Auto-approve
            uses: hmarr/auto-approve-action@v2.0.0
            with:
              github-token: ${{ secrets.OTTO_TOKEN }}

          - name: Auto-merge
            uses: "pascalgn/automerge-action@v0.8.4"
            env:
              GITHUB_TOKEN: "${{ secrets.OTTO_TOKEN }}"
              MERGE_LABELS: ""
              MERGE_METHOD: squash
