name: Checks

on:
  pull_request:
    types: [opened, synchronize, reopened, edited, ready_for_review]
    branches:
      - master

jobs:
    commit_lint:
      name: Lint commit messages
      runs-on: ubuntu-latest
      env:
        GITHUB_TOKEN: ${{ secrets.OTTO_TOKEN }}

      steps:
        - name: Check out code
          uses: actions/checkout@v2.3.3
          with:
            fetch-depth: 0
            ref: ${{ github.event.pull_request.head.ref }}

        - name: Lint commit messages
          uses: wagoid/commitlint-github-action@v2.1.0
          with:
            failOnWarnings: true

        - uses: amannn/action-semantic-pull-request@v2.0.0

    test_build:
      name: Test Docker build
      runs-on: ubuntu-latest

      steps:
        - name: Checkout code
          uses: actions/checkout@v2.3.3
          with:
            ref: ${{ github.event.pull_request.head.ref }}

        - name: Lint Dockerfile
          uses: brpaz/hadolint-action@v1.1.0

        - name: Test build
          run: make docker-build
          env:
            GOOGLE_APPLICATION_CREDENTIALS_ENCODED: ${{ secrets.GCP_REGISTRY_KEY }}
            GOOGLE_APPLICATION_CREDENTIALS: ${HOME}/secrets/default_application_credentials.json

    auto_merge_dependabot:
        name: Auto-approve dependabot pull requests
        runs-on: ubuntu-latest
        needs: [test_build]

        if: github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]'

        steps:
          - name: Auto-approve
            uses: hmarr/auto-approve-action@v2.0.0
            with:
              github-token: ${{ secrets.OTTO_TOKEN }}

          - name: Auto-merge
            uses: pascalgn/automerge-action@v0.12.0
            env:
              GITHUB_TOKEN: "${{ secrets.OTTO_TOKEN }}"
              MERGE_LABELS: ""
              MERGE_METHOD: squash
