name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
    build_push:
      name: Build & push Docker image
      runs-on: ubuntu-latest
      if: github.event.base_ref == 'refs/heads/master'

      steps:
        - name: Check out code
          uses: actions/checkout@v2.3.3
          with:
            ref: master

        - name: Build & push
          run: make docker-push
          env:
            GOOGLE_APPLICATION_CREDENTIALS_ENCODED: ${{ secrets.GCP_REGISTRY_KEY }}
            GOOGLE_APPLICATION_CREDENTIALS: ${HOME}/secrets/default_application_credentials.json
            DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
            DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
